### ISSUE TITLE
rails generation not needed

### ISSUE THREAD

**Issue by mystycs** [learn-co-students/rendering-collections-lab-v-000#94]
this lesson doesnt need controllers and models created yet the lesson can be confusing with this part of the readme

> First, fork and clone this lab. Before anything, note that when you generate models, controllers, etc, be sure to include this option, so that it skips tests (which we already have): --no-test-framework

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
